{{- if  or (eq .Requirements.repository "nexus") (eq .Requirements.repository "") }}
enabled: true
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 32Gi
{{- else }}
enabled: false
{{- end }}
